server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: app
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /orderStatuses/**, /menus/**
        - id: pay
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**, 
        - id: store
          uri: http://localhost:8083
          predicates:
            - Path=/orderProcessings/**, /orderViews/**
        - id: customer
          uri: http://localhost:8084
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: app
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /orderStatuses/**, /menus/**
        - id: pay
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**, 
        - id: store
          uri: http://localhost:8083
          predicates:
            - Path=/orderProcessings/**, /orderViews/**
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
